/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJAWTWorld */

#ifndef _Included_HelloJAWTWorld
#define _Included_HelloJAWTWorld
#ifdef __cplusplus
extern "C" {
#endif
#undef HelloJAWTWorld_FOCUS_TRAVERSABLE_UNKNOWN
#define HelloJAWTWorld_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef HelloJAWTWorld_FOCUS_TRAVERSABLE_DEFAULT
#define HelloJAWTWorld_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef HelloJAWTWorld_FOCUS_TRAVERSABLE_SET
#define HelloJAWTWorld_FOCUS_TRAVERSABLE_SET 2L
#undef HelloJAWTWorld_TOP_ALIGNMENT
#define HelloJAWTWorld_TOP_ALIGNMENT 0.0f
#undef HelloJAWTWorld_CENTER_ALIGNMENT
#define HelloJAWTWorld_CENTER_ALIGNMENT 0.5f
#undef HelloJAWTWorld_BOTTOM_ALIGNMENT
#define HelloJAWTWorld_BOTTOM_ALIGNMENT 1.0f
#undef HelloJAWTWorld_LEFT_ALIGNMENT
#define HelloJAWTWorld_LEFT_ALIGNMENT 0.0f
#undef HelloJAWTWorld_RIGHT_ALIGNMENT
#define HelloJAWTWorld_RIGHT_ALIGNMENT 1.0f
#undef HelloJAWTWorld_serialVersionUID
#define HelloJAWTWorld_serialVersionUID -7644114512714619750LL
#undef HelloJAWTWorld_serialVersionUID
#define HelloJAWTWorld_serialVersionUID -2284879212465893870LL
/*
 * Class:     HelloJAWTWorld
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_HelloJAWTWorld_paint
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
